package com.danidomenech.dndlootforge.ui.utils

import com.danidomenech.dndlootforge.data.model.ItemType

val typeOrder = listOf(
    ItemType.POTION,
    ItemType.CONSUMABLE,
    ItemType.AMMUNITION,
    ItemType.SCROLL,
    ItemType.MAGICAL_TOOL,
    ItemType.CLOTHING,
    ItemType.LIGHT_ARMOR,
    ItemType.MEDIUM_ARMOR,
    ItemType.HEAVY_ARMOR,
    ItemType.ARMOR,
    ItemType.HELMET,
    ItemType.GLOVES,
    ItemType.BOOTS,
    ItemType.CLOAK,
    ItemType.ACCESSORY,
    ItemType.NECKLACE,
    ItemType.RING,
    ItemType.SHIELD,
    ItemType.WEAPON,
    ItemType.DAGGER,
    ItemType.SHORT_SWORD,
    ItemType.LONG_SWORD,
    ItemType.GREATSWORD,
    ItemType.HAND_AXE,
    ItemType.BATTLE_AXE,
    ItemType.GREATAXE,
    ItemType.WARHAMMER,
    ItemType.MAUL,
    ItemType.SHORT_BOW,
    ItemType.LONG_BOW,
    ItemType.HAND_CROSSBOW,
    ItemType.LIGHT_CROSSBOW,
    ItemType.HEAVY_CROSSBOW,
    ItemType.TRIDENT,
    ItemType.JAVELIN,
    ItemType.STAFF,
    ItemType.ROD,
    ItemType.WAND
)